### ISSUE TITLE
bug: shared flow with mfa on is giving 403

### ISSUE THREAD

**Issue by ltutar** [xebialabs-community/xld-apigee-plugin#23]
when mfa is turned on and the api type is shared_flow, then the plugin fails.

2018-01-12 12:22:03.093 [task-sys-task.step-dispatcher-40] {stepDescription=Deploying shared flow 'helloworld-flow-v1' to environment 'prod', taskId=4ee33e07-74dc-4a21-974e-91d1ec5234da, username=admin} ERROR c.x.deployit.plugin.steps.JythonStep - Error while executing script [apigee/upload-shared-flow-and-deploy.py]: ValueError: No JSON object could be decoded in <script> at line number 16
com.xebialabs.platform.script.jython.JythonException: Error while executing script [apigee/upload-shared-flow-and-deploy.py]: ValueError: No JSON object could be decoded in <script> at line number 16
	at com.xebialabs.platform.script.jython.JythonException$.apply(JythonException.scala:17)
	at com.xebialabs.platform.script.jython.JythonSupport$$anonfun$executeScript$3.apply(JythonSupport.scala:45)
	at com.xebialabs.platform.script.jython.JythonSupport$class.withThreadLocalWriter(JythonSupport.scala:52)
	at com.xebialabs.platform.script.jython.JythonSupport$class.executeScript(JythonSupport.scala:40)
	at com.xebialabs.deployit.plugin.steps.JythonStep$$anon$1.executeScript(JythonStep.scala:27)
	at com.xebialabs.platform.script.jython.JythonSupport$class.executeScript(JythonSupport.scala:35)
	at com.xebialabs.deployit.plugin.steps.JythonStep$$anon$1.executeScript(JythonStep.scala:27)

**Comment by ltutar** [comment]
This was because I  was missing  rights for shared_flow  actions.
