### ISSUE TITLE
bug: password in clear text when there is a connection error

### ISSUE THREAD

**Issue by ltutar** [xebialabs-community/xld-apigee-plugin#5]
> Error while executing script [apigee/deploy-api.py]: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='login.apigee.com', port=443): Max retries exceeded with url: /oauth/token?mfa_token=123456&password=blabla%21&grant_type=password&username=ltutar%40xebia.com (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2>: Failed to establish a new connection: [Errno -1] Unmapped exception: org.python.netty.channel.ConnectTimeoutException: connection timed out: login.apigee.com/11.123.11.123:443',)) in <script> at line number 17 
> com.xebialabs.platform.script.jython.JythonException: Error while executing script [apigee/deploy-api.py]: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='login.apigee.com', port=443): Max retries exceeded with url: /oauth/token?mfa_token=123456&password=blabla%21&grant_type=password&username=ltutar%40xebia.com (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2>: Failed to establish a new connection: [Errno -1] Unmapped exception: org.python.netty.channel.ConnectTimeoutException: connection timed out: login.apigee.com/11.123.11.123:443',)) in <script> at line number 17 

This is only the case when MFA is on. Otherwise you get the error:

> https://api.enterprise.apigee.com/v1/o/ltutar-trial/environments/test/apis/helloworld/revisions/1/deployments 
Multi factor authentication is off 
Error while executing script [apigee/deploy-api.py]: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.enterprise.apigee.com', port=443): Max retries exceeded with url: /v1/o/ltutar-trial/environments/test/apis/helloworld/revisions/1/deployments?override=true (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x3>: Failed to establish a new connection: [Errno -1] Unmapped exception: org.python.netty.channel.ConnectTimeoutException: connection timed out: api.enterprise.apigee.com/11.123.11.123:443',)) in <script> at line number 17 
com.xebialabs.platform.script.jython.JythonException: Error while executing script [apigee/deploy-api.py]: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.enterprise.apigee.com', port=443): Max retries exceeded with url: /v1/o/ltutar-trial/environments/test/apis/helloworld/revisions/1/deployments?override=true (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x3>: Failed to establish a new connection: [Errno -1] Unmapped exception: org.python.netty.channel.ConnectTimeoutException: connection timed out: api.enterprise.apigee.com/11.123.11.123:443',)) in <script> at line number 17 
at com.xebialabs.platform.script.jython.JythonException$.apply(JythonException.scala:17) 
at com.xebialabs.platform.script.jython.JythonSupport$$anonfun$executeScript$3.apply(JythonSupport.scala:45) 
at com.xebialabs.platform.script.jython.JythonSupport$class.withThreadLocalWriter(JythonSupport.scala:52) 
at com.xebialabs.platform.script.jython.JythonSupport$class.executeScript(JythonSupport.scala:40) 
at com.xebialabs.deployit.plugin.steps.JythonStep$$anon$1.executeScript(JythonStep.scala:27) 
at com.xebialabs.platform.script.jython.JythonSupport$class.executeScript(JythonSupport.scala:35) 
at com.xebialabs.deployit.plugin.steps.JythonStep$$anon$1.executeScript(JythonStep.scala:27) 
at com.xebialabs.deployit.plugin.steps.JythonStep.executeScript(JythonStep.scala:66) 
at com.xebialabs.deployit.plugin.steps.JythonStep.execute(JythonStep.scala:57) 
at com.xebialabs.deployit.engine.tasker.StepExecutingActor$$anonfun$1$$anonfun$apply$3.apply(StepExecutingActor.scala:128) 
at com.xebialabs.deployit.engine.tasker.MdcUtils$.withMdc(MdcUtils.scala:16) 
at com.xebialabs.deployit.engine.tasker.StepExecutingActor$$anonfun$1.apply(StepExecutingActor.scala:117) 
at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) 
at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) 
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
at java.lang.Thread.run(Thread.java:748) 
Caused by: javax.script.ScriptException: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.enterprise.apigee.com', port=443): Max retries exceeded with url: /v1/o/ltutar-trial/environments/test/apis/helloworld/revisions/1/deployments?override=true (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x3>: Failed to establish a new connection: [Errno -1] Unmapped exception: org.python.netty.channel.ConnectTimeoutException: connection timed out: api.enterprise.apigee.com/11.123.11.123:443',)) in <script> at line number 17 
at org.python.jsr223.PyScriptEngine.scriptException(PyScriptEngine.java:202) 
at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:42) 
at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31) 
at com.xebialabs.platform.script.jython.JythonSupport$$anonfun$executeScript$3.apply(JythonSupport.scala:42) 
... 16 more

**Comment by ltutar** [comment]
The error occurs at https://github.com/xebialabs-community/xld-apigee-plugin/blob/master/src/main/resources/apigee/__init__.py#L90 
The next line will not be executed.
Possible solutions:
1) Check the connection without the header with the password?
2) Upgrade requests library? Updating to latest requests library does not solve the problem.
